[package]
name = "spalhad-spec"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
sha3 = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
thiserror = { workspace = true }
